import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main>
          <Header />
          <div className="container mx-auto mt-[100px] px-4">
            <h1 className="font-bold py-10 text-2xl">simple blog app with Nextjs - mongoDb - tailwin css</h1>
            {children}
          </div>
        </main>
      </body>
    </html>
  );
}
